title: Pedro J. Márquez
email: pedro@pjmarquez.com
description: >- # this means to ignore newlines until "baseurl:"
  Portfolio website of cinematographer and photographer Pedro J.Marquéz
baseurl: "/" 
url: "https://pjmarquez.com" 

# Build settings
permalink: pretty
plugins:
  - jekyll-feed

sass:
  sass_dir: _sass

collections:
  photo: 
    output: true
  cinema:
    output: true


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
