---
label: project
hide_body: true
fields:
- type: text
  name: layout
  label: layout
- type: text
  name: title
  label: title
- type: boolean
  name: mainProject
  label: mainProject
- type: image_gallery
  name: images
  label: images
- name: add_the_images_for_this_project
  type: image_gallery
  config: {}
  label: Add the images for this project
